// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'message.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'streams.dart';
part 'api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IncomingRequest`, `PubSubMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `create_event_stream`

/// Polls for pending events from the global broadcaster.
/// Returns a list of events that have been received since the last poll.
/// This is a polling fallback for when streaming isn't available.
///
/// # Arguments
/// * `max_events` - Maximum number of events to return (bounded to prevent memory issues)
///
/// # Returns
/// List of pending events (may be empty if none available).
Future<List<KoriumEvent>> pollEvents({required int maxEvents}) =>
    RustLib.instance.api.crateApiPollEvents(maxEvents: maxEvents);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KoriumNode>>
abstract class KoriumNode implements RustOpaqueInterface {
  /// Bootstraps the node by connecting to an existing peer.
  ///
  /// # Arguments
  /// * `peer_identity` - The identity (hex) of the bootstrap peer
  /// * `peer_addrs` - List of addresses to try for this peer
  Future<void> bootstrap({
    required String peerIdentity,
    required List<String> peerAddrs,
  });

  /// Returns the bootstrap error message if bootstrap failed.
  /// Returns None if bootstrap succeeded or hasn't been attempted.
  String? get bootstrapError;

  /// Creates a new Korium node with default configuration.
  ///
  /// # Arguments
  /// * `bind_addr` - Address to bind to (e.g., "0.0.0.0:0")
  ///
  /// # Returns
  /// A new `KoriumNode` instance.
  ///
  /// # Errors
  /// Returns `KoriumError` if node creation fails.
  static Future<KoriumNode> create({required String bindAddr}) =>
      RustLib.instance.api.crateApiKoriumNodeCreate(bindAddr: bindAddr);

  /// Creates a new Korium node with full configuration.
  ///
  /// Automatically bootstraps to the public Korium network via DNS resolution
  /// of bootstrap.korium.io.
  static Future<KoriumNode> createWithConfig({required NodeConfig config}) =>
      RustLib.instance.api.crateApiKoriumNodeCreateWithConfig(config: config);

  /// Finds peers near a target identity in the DHT.
  ///
  /// # Arguments
  /// * `target_id` - The target identity to search near
  ///
  /// # Returns
  /// List of peer identities found.
  Future<List<String>> findPeers({required String targetId});

  /// Gets peers from the DHT routing table.
  ///
  /// Searches for peers near this node's identity in the DHT.
  /// Returns a list of peers with their identities and addresses.
  Future<List<DhtPeer>> getDhtPeers();

  /// Returns identity restoration data for saving to secure storage.
  ///
  /// This method returns the private key and PoW nonce needed to restore
  /// the node's identity on subsequent app launches without re-computing PoW.
  ///
  /// # Security
  /// - MUST be stored in secure storage (iOS Keychain / Android Keystore)
  /// - This method can only be called ONCE per node instance
  /// - Subsequent calls return None (one-shot extraction to minimize exposure)
  /// - The secret key allows full identity impersonation - treat as password
  ///
  /// # Returns
  /// - `Some(IdentityRestoreData)` on first call after node creation
  /// - `None` on subsequent calls (data already extracted)
  IdentityRestoreData? getIdentityRestoreData();

  /// Returns the node's identity (Ed25519 public key as hex string).
  String get identity;

  /// Returns whether the node has successfully bootstrapped to the Korium network.
  bool get isBootstrapped;

  /// Checks if a peer is reachable by resolving their address.
  /// Returns true if the peer has published addresses, false otherwise.
  Future<bool> isPeerOnline({required String peerId});

  /// Returns the local address the node is listening on.
  String get localAddr;

  /// Returns the primary routable address for DHT publishing.
  ///
  /// This returns the first non-loopback routable address, suitable for
  /// peer discovery.
  Future<String> primaryRoutableAddress();

  /// Publishes a message to a PubSub topic.
  ///
  /// # Arguments
  /// * `topic` - The topic to publish to
  /// * `data` - The message data
  Future<void> publish({required String topic, required List<int> data});

  /// Publishes the node's address for peer discovery.
  ///
  /// # Arguments
  /// * `addresses` - List of addresses where this node can be reached
  Future<void> publishAddress({required List<String> addresses});

  /// Resolves a peer's contact information.
  ///
  /// # Arguments
  /// * `peer_id` - The identity to resolve
  ///
  /// # Returns
  /// List of addresses where the peer can be reached.
  Future<List<String>> resolvePeer({required String peerId});

  /// Returns routable addresses for this node.
  ///
  /// When bound to `0.0.0.0`, this enumerates all local network interfaces
  /// and returns their addresses with the bound port. This is suitable for
  /// peer discovery.
  ///
  /// Loopback addresses (127.0.0.1) are excluded.
  Future<List<String>> routableAddresses();

  /// Sends a chat message to a peer.
  ///
  /// # Arguments
  /// * `peer_id` - The identity of the recipient
  /// * `message` - The chat message to send
  ///
  /// # Returns
  /// The sent message with updated status.
  Future<ChatMessage> sendMessage({
    required String peerId,
    required ChatMessage message,
  });

  /// Sends a request to a peer and waits for a response.
  ///
  /// # Arguments
  /// * `peer_id` - The identity of the target peer
  /// * `data` - The request data
  ///
  /// # Returns
  /// The response data from the peer.
  Future<Uint8List> sendRequest({
    required String peerId,
    required List<int> data,
  });

  /// Gracefully shuts down the node.
  Future<void> shutdown();

  /// Starts listening for incoming messages and requests.
  /// This spawns background tasks that forward events to the event broadcaster.
  /// Call this after node creation to receive incoming messages.
  Future<void> startListeners();

  /// Subscribes to a PubSub topic.
  ///
  /// # Arguments
  /// * `topic` - The topic name to subscribe to
  Future<void> subscribe({required String topic});
}

/// A peer discovered in the DHT (Distributed Hash Table).
@freezed
sealed class DhtPeer with _$DhtPeer {
  const factory DhtPeer({
    required String identity,
    required List<String> addresses,
  }) = _DhtPeer;
}

/// Identity restoration data for saving to secure storage.
///
/// This contains the private key and PoW nonce needed to restore the node's
/// identity on subsequent launches without re-computing PoW.
///
/// # Security
/// This data is HIGHLY SENSITIVE. The `secret_key_hex` is the node's private key.
/// It MUST be stored in secure storage (e.g., iOS Keychain, Android Keystore).
/// Leaking this data allows identity theft.
@freezed
sealed class IdentityRestoreData with _$IdentityRestoreData {
  const factory IdentityRestoreData({
    required String secretKeyHex,
    required BigInt powNonce,
  }) = _IdentityRestoreData;
}

/// Configuration for creating a new Korium node.
@freezed
sealed class NodeConfig with _$NodeConfig {
  const NodeConfig._();
  const factory NodeConfig({
    required String bindAddr,
    String? namespaceSecret,
    String? privateKeyHex,
    BigInt? identityProofNonce,
  }) = _NodeConfig;
  static Future<NodeConfig> default_() =>
      RustLib.instance.api.crateApiNodeConfigDefault();
}
