// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class KoriumError with _$KoriumError implements FrbException {
  const KoriumError._();

  /// Failed to bind to the specified address.
  const factory KoriumError.bindError(String field0) = KoriumError_BindError;

  /// Failed to bootstrap with the specified peer.
  const factory KoriumError.bootstrapError(String field0) =
      KoriumError_BootstrapError;

  /// Failed to connect to a peer.
  const factory KoriumError.connectionError(String field0) =
      KoriumError_ConnectionError;

  /// Failed to send a message.
  const factory KoriumError.sendError(String field0) = KoriumError_SendError;

  /// Failed to receive a message.
  const factory KoriumError.receiveError(String field0) =
      KoriumError_ReceiveError;

  /// The specified peer was not found.
  const factory KoriumError.peerNotFound(String field0) =
      KoriumError_PeerNotFound;

  /// The operation timed out.
  const factory KoriumError.timeout(String field0) = KoriumError_Timeout;

  /// Invalid identity format.
  const factory KoriumError.invalidIdentity(String field0) =
      KoriumError_InvalidIdentity;

  /// Serialization/deserialization error.
  const factory KoriumError.serializationError(String field0) =
      KoriumError_SerializationError;

  /// Node is not initialized.
  const factory KoriumError.notInitialized() = KoriumError_NotInitialized;

  /// Node is already shut down.
  const factory KoriumError.shutDown() = KoriumError_ShutDown;

  /// Internal error.
  const factory KoriumError.internal(String field0) = KoriumError_Internal;
}
