// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'message.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'streams.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1128056080;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'six7_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiKoriumNodeBootstrap({
    required KoriumNode that,
    required String peerIdentity,
    required List<String> peerAddrs,
  });

  String? crateApiKoriumNodeBootstrapError({required KoriumNode that});

  Future<KoriumNode> crateApiKoriumNodeCreate({required String bindAddr});

  Future<KoriumNode> crateApiKoriumNodeCreateWithConfig({
    required NodeConfig config,
  });

  Future<List<String>> crateApiKoriumNodeFindPeers({
    required KoriumNode that,
    required String targetId,
  });

  Future<List<DhtPeer>> crateApiKoriumNodeGetDhtPeers({
    required KoriumNode that,
  });

  IdentityRestoreData? crateApiKoriumNodeGetIdentityRestoreData({
    required KoriumNode that,
  });

  String crateApiKoriumNodeIdentity({required KoriumNode that});

  bool crateApiKoriumNodeIsBootstrapped({required KoriumNode that});

  Future<bool> crateApiKoriumNodeIsPeerOnline({
    required KoriumNode that,
    required String peerId,
  });

  String crateApiKoriumNodeLocalAddr({required KoriumNode that});

  Future<String> crateApiKoriumNodePrimaryRoutableAddress({
    required KoriumNode that,
  });

  Future<void> crateApiKoriumNodePublish({
    required KoriumNode that,
    required String topic,
    required List<int> data,
  });

  Future<void> crateApiKoriumNodePublishAddress({
    required KoriumNode that,
    required List<String> addresses,
  });

  Future<List<String>> crateApiKoriumNodeResolvePeer({
    required KoriumNode that,
    required String peerId,
  });

  Future<List<String>> crateApiKoriumNodeRoutableAddresses({
    required KoriumNode that,
  });

  Future<ChatMessage> crateApiKoriumNodeSendMessage({
    required KoriumNode that,
    required String peerId,
    required ChatMessage message,
  });

  Future<Uint8List> crateApiKoriumNodeSendRequest({
    required KoriumNode that,
    required String peerId,
    required List<int> data,
  });

  Future<void> crateApiKoriumNodeShutdown({required KoriumNode that});

  Future<void> crateApiKoriumNodeStartListeners({required KoriumNode that});

  Future<void> crateApiKoriumNodeSubscribe({
    required KoriumNode that,
    required String topic,
  });

  Future<NodeConfig> crateApiNodeConfigDefault();

  Future<List<KoriumEvent>> crateApiPollEvents({required int maxEvents});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KoriumNode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KoriumNode;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KoriumNodePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiKoriumNodeBootstrap({
    required KoriumNode that,
    required String peerIdentity,
    required List<String> peerAddrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(peerIdentity);
          var arg2 = cst_encode_list_String(peerAddrs);
          return wire.wire__crate__api__KoriumNode_bootstrap(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeBootstrapConstMeta,
        argValues: [that, peerIdentity, peerAddrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeBootstrapConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_bootstrap",
        argNames: ["that", "peerIdentity", "peerAddrs"],
      );

  @override
  String? crateApiKoriumNodeBootstrapError({required KoriumNode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_bootstrap_error(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeBootstrapErrorConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeBootstrapErrorConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_bootstrap_error",
        argNames: ["that"],
      );

  @override
  Future<KoriumNode> crateApiKoriumNodeCreate({required String bindAddr}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(bindAddr);
          return wire.wire__crate__api__KoriumNode_create(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeCreateConstMeta,
        argValues: [bindAddr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeCreateConstMeta => const TaskConstMeta(
    debugName: "KoriumNode_create",
    argNames: ["bindAddr"],
  );

  @override
  Future<KoriumNode> crateApiKoriumNodeCreateWithConfig({
    required NodeConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_node_config(config);
          return wire.wire__crate__api__KoriumNode_create_with_config(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeCreateWithConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeCreateWithConfigConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_create_with_config",
        argNames: ["config"],
      );

  @override
  Future<List<String>> crateApiKoriumNodeFindPeers({
    required KoriumNode that,
    required String targetId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(targetId);
          return wire.wire__crate__api__KoriumNode_find_peers(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeFindPeersConstMeta,
        argValues: [that, targetId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeFindPeersConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_find_peers",
        argNames: ["that", "targetId"],
      );

  @override
  Future<List<DhtPeer>> crateApiKoriumNodeGetDhtPeers({
    required KoriumNode that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_get_dht_peers(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_dht_peer,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeGetDhtPeersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeGetDhtPeersConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_get_dht_peers",
        argNames: ["that"],
      );

  @override
  IdentityRestoreData? crateApiKoriumNodeGetIdentityRestoreData({
    required KoriumNode that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_get_identity_restore_data(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_identity_restore_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeGetIdentityRestoreDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeGetIdentityRestoreDataConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_get_identity_restore_data",
        argNames: ["that"],
      );

  @override
  String crateApiKoriumNodeIdentity({required KoriumNode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_identity(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeIdentityConstMeta =>
      const TaskConstMeta(debugName: "KoriumNode_identity", argNames: ["that"]);

  @override
  bool crateApiKoriumNodeIsBootstrapped({required KoriumNode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_is_bootstrapped(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeIsBootstrappedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeIsBootstrappedConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_is_bootstrapped",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiKoriumNodeIsPeerOnline({
    required KoriumNode that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(peerId);
          return wire.wire__crate__api__KoriumNode_is_peer_online(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeIsPeerOnlineConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeIsPeerOnlineConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_is_peer_online",
        argNames: ["that", "peerId"],
      );

  @override
  String crateApiKoriumNodeLocalAddr({required KoriumNode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_local_addr(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeLocalAddrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeLocalAddrConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_local_addr",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiKoriumNodePrimaryRoutableAddress({
    required KoriumNode that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_primary_routable_address(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodePrimaryRoutableAddressConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodePrimaryRoutableAddressConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_primary_routable_address",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiKoriumNodePublish({
    required KoriumNode that,
    required String topic,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(topic);
          var arg2 = cst_encode_list_prim_u_8_loose(data);
          return wire.wire__crate__api__KoriumNode_publish(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodePublishConstMeta,
        argValues: [that, topic, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodePublishConstMeta => const TaskConstMeta(
    debugName: "KoriumNode_publish",
    argNames: ["that", "topic", "data"],
  );

  @override
  Future<void> crateApiKoriumNodePublishAddress({
    required KoriumNode that,
    required List<String> addresses,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_list_String(addresses);
          return wire.wire__crate__api__KoriumNode_publish_address(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodePublishAddressConstMeta,
        argValues: [that, addresses],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodePublishAddressConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_publish_address",
        argNames: ["that", "addresses"],
      );

  @override
  Future<List<String>> crateApiKoriumNodeResolvePeer({
    required KoriumNode that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(peerId);
          return wire.wire__crate__api__KoriumNode_resolve_peer(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeResolvePeerConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeResolvePeerConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_resolve_peer",
        argNames: ["that", "peerId"],
      );

  @override
  Future<List<String>> crateApiKoriumNodeRoutableAddresses({
    required KoriumNode that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_routable_addresses(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKoriumNodeRoutableAddressesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeRoutableAddressesConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_routable_addresses",
        argNames: ["that"],
      );

  @override
  Future<ChatMessage> crateApiKoriumNodeSendMessage({
    required KoriumNode that,
    required String peerId,
    required ChatMessage message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(peerId);
          var arg2 = cst_encode_box_autoadd_chat_message(message);
          return wire.wire__crate__api__KoriumNode_send_message(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_chat_message,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeSendMessageConstMeta,
        argValues: [that, peerId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_send_message",
        argNames: ["that", "peerId", "message"],
      );

  @override
  Future<Uint8List> crateApiKoriumNodeSendRequest({
    required KoriumNode that,
    required String peerId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(peerId);
          var arg2 = cst_encode_list_prim_u_8_loose(data);
          return wire.wire__crate__api__KoriumNode_send_request(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeSendRequestConstMeta,
        argValues: [that, peerId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeSendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_send_request",
        argNames: ["that", "peerId", "data"],
      );

  @override
  Future<void> crateApiKoriumNodeShutdown({required KoriumNode that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_shutdown(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeShutdownConstMeta =>
      const TaskConstMeta(debugName: "KoriumNode_shutdown", argNames: ["that"]);

  @override
  Future<void> crateApiKoriumNodeStartListeners({required KoriumNode that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          return wire.wire__crate__api__KoriumNode_start_listeners(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeStartListenersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeStartListenersConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_start_listeners",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiKoriumNodeSubscribe({
    required KoriumNode that,
    required String topic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
                that,
              );
          var arg1 = cst_encode_String(topic);
          return wire.wire__crate__api__KoriumNode_subscribe(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_korium_error,
        ),
        constMeta: kCrateApiKoriumNodeSubscribeConstMeta,
        argValues: [that, topic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKoriumNodeSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "KoriumNode_subscribe",
        argNames: ["that", "topic"],
      );

  @override
  Future<NodeConfig> crateApiNodeConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__node_config_default(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_node_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "node_config_default", argNames: []);

  @override
  Future<List<KoriumEvent>> crateApiPollEvents({required int maxEvents}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_i_32(maxEvents);
          return wire.wire__crate__api__poll_events(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_korium_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPollEventsConstMeta,
        argValues: [maxEvents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollEventsConstMeta =>
      const TaskConstMeta(debugName: "poll_events", argNames: ["maxEvents"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KoriumNode => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KoriumNode => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode;

  @protected
  KoriumNode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KoriumNode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KoriumNode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  IdentityRestoreData dco_decode_box_autoadd_identity_restore_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_identity_restore_data(raw);
  }

  @protected
  NodeConfig dco_decode_box_autoadd_node_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_node_config(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ChatMessage(
      id: dco_decode_String(arr[0]),
      senderId: dco_decode_String(arr[1]),
      recipientId: dco_decode_String(arr[2]),
      text: dco_decode_String(arr[3]),
      messageType: dco_decode_message_type(arr[4]),
      timestampMs: dco_decode_i_64(arr[5]),
      status: dco_decode_message_status(arr[6]),
      isFromMe: dco_decode_bool(arr[7]),
      replyToId: dco_decode_opt_String(arr[8]),
      mediaUrl: dco_decode_opt_String(arr[9]),
      thumbnailUrl: dco_decode_opt_String(arr[10]),
      mediaSizeBytes: dco_decode_opt_box_autoadd_i_64(arr[11]),
      mediaDurationMs: dco_decode_opt_box_autoadd_i_64(arr[12]),
    );
  }

  @protected
  DhtPeer dco_decode_dht_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DhtPeer(
      identity: dco_decode_String(arr[0]),
      addresses: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityRestoreData dco_decode_identity_restore_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityRestoreData(
      secretKeyHex: dco_decode_String(arr[0]),
      powNonce: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  KoriumError dco_decode_korium_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return KoriumError_BindError(dco_decode_String(raw[1]));
      case 1:
        return KoriumError_BootstrapError(dco_decode_String(raw[1]));
      case 2:
        return KoriumError_ConnectionError(dco_decode_String(raw[1]));
      case 3:
        return KoriumError_SendError(dco_decode_String(raw[1]));
      case 4:
        return KoriumError_ReceiveError(dco_decode_String(raw[1]));
      case 5:
        return KoriumError_PeerNotFound(dco_decode_String(raw[1]));
      case 6:
        return KoriumError_Timeout(dco_decode_String(raw[1]));
      case 7:
        return KoriumError_InvalidIdentity(dco_decode_String(raw[1]));
      case 8:
        return KoriumError_SerializationError(dco_decode_String(raw[1]));
      case 9:
        return KoriumError_NotInitialized();
      case 10:
        return KoriumError_ShutDown();
      case 11:
        return KoriumError_Internal(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  KoriumEvent dco_decode_korium_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return KoriumEvent_PubSubMessage(
          topic: dco_decode_String(raw[1]),
          fromIdentity: dco_decode_String(raw[2]),
          data: dco_decode_list_prim_u_8_strict(raw[3]),
        );
      case 1:
        return KoriumEvent_IncomingRequest(
          fromIdentity: dco_decode_String(raw[1]),
          requestId: dco_decode_String(raw[2]),
          data: dco_decode_list_prim_u_8_strict(raw[3]),
        );
      case 2:
        return KoriumEvent_ChatMessageReceived(
          message: dco_decode_box_autoadd_chat_message(raw[1]),
        );
      case 3:
        return KoriumEvent_MessageStatusUpdate(
          messageId: dco_decode_String(raw[1]),
          status: dco_decode_message_status(raw[2]),
        );
      case 4:
        return KoriumEvent_ConnectionStateChanged(
          isConnected: dco_decode_bool(raw[1]),
        );
      case 5:
        return KoriumEvent_PeerPresenceChanged(
          peerIdentity: dco_decode_String(raw[1]),
          isOnline: dco_decode_bool(raw[2]),
        );
      case 6:
        return KoriumEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DhtPeer> dco_decode_list_dht_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dht_peer).toList();
  }

  @protected
  List<KoriumEvent> dco_decode_list_korium_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_korium_event).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageStatus dco_decode_message_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageStatus.values[raw as int];
  }

  @protected
  MessageType dco_decode_message_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageType.values[raw as int];
  }

  @protected
  NodeConfig dco_decode_node_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NodeConfig(
      bindAddr: dco_decode_String(arr[0]),
      namespaceSecret: dco_decode_opt_String(arr[1]),
      privateKeyHex: dco_decode_opt_String(arr[2]),
      identityProofNonce: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  IdentityRestoreData? dco_decode_opt_box_autoadd_identity_restore_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_identity_restore_data(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  KoriumNode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KoriumNode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KoriumNode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KoriumNodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  IdentityRestoreData sse_decode_box_autoadd_identity_restore_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_identity_restore_data(deserializer));
  }

  @protected
  NodeConfig sse_decode_box_autoadd_node_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_node_config(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_recipientId = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_messageType = sse_decode_message_type(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_status = sse_decode_message_status(deserializer);
    var var_isFromMe = sse_decode_bool(deserializer);
    var var_replyToId = sse_decode_opt_String(deserializer);
    var var_mediaUrl = sse_decode_opt_String(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    var var_mediaSizeBytes = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_mediaDurationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    return ChatMessage(
      id: var_id,
      senderId: var_senderId,
      recipientId: var_recipientId,
      text: var_text,
      messageType: var_messageType,
      timestampMs: var_timestampMs,
      status: var_status,
      isFromMe: var_isFromMe,
      replyToId: var_replyToId,
      mediaUrl: var_mediaUrl,
      thumbnailUrl: var_thumbnailUrl,
      mediaSizeBytes: var_mediaSizeBytes,
      mediaDurationMs: var_mediaDurationMs,
    );
  }

  @protected
  DhtPeer sse_decode_dht_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identity = sse_decode_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    return DhtPeer(identity: var_identity, addresses: var_addresses);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityRestoreData sse_decode_identity_restore_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKeyHex = sse_decode_String(deserializer);
    var var_powNonce = sse_decode_u_64(deserializer);
    return IdentityRestoreData(
      secretKeyHex: var_secretKeyHex,
      powNonce: var_powNonce,
    );
  }

  @protected
  KoriumError sse_decode_korium_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_BindError(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_BootstrapError(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_ConnectionError(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_SendError(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_ReceiveError(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_PeerNotFound(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_Timeout(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_InvalidIdentity(var_field0);
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_SerializationError(var_field0);
      case 9:
        return KoriumError_NotInitialized();
      case 10:
        return KoriumError_ShutDown();
      case 11:
        var var_field0 = sse_decode_String(deserializer);
        return KoriumError_Internal(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  KoriumEvent sse_decode_korium_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_topic = sse_decode_String(deserializer);
        var var_fromIdentity = sse_decode_String(deserializer);
        var var_data = sse_decode_list_prim_u_8_strict(deserializer);
        return KoriumEvent_PubSubMessage(
          topic: var_topic,
          fromIdentity: var_fromIdentity,
          data: var_data,
        );
      case 1:
        var var_fromIdentity = sse_decode_String(deserializer);
        var var_requestId = sse_decode_String(deserializer);
        var var_data = sse_decode_list_prim_u_8_strict(deserializer);
        return KoriumEvent_IncomingRequest(
          fromIdentity: var_fromIdentity,
          requestId: var_requestId,
          data: var_data,
        );
      case 2:
        var var_message = sse_decode_box_autoadd_chat_message(deserializer);
        return KoriumEvent_ChatMessageReceived(message: var_message);
      case 3:
        var var_messageId = sse_decode_String(deserializer);
        var var_status = sse_decode_message_status(deserializer);
        return KoriumEvent_MessageStatusUpdate(
          messageId: var_messageId,
          status: var_status,
        );
      case 4:
        var var_isConnected = sse_decode_bool(deserializer);
        return KoriumEvent_ConnectionStateChanged(isConnected: var_isConnected);
      case 5:
        var var_peerIdentity = sse_decode_String(deserializer);
        var var_isOnline = sse_decode_bool(deserializer);
        return KoriumEvent_PeerPresenceChanged(
          peerIdentity: var_peerIdentity,
          isOnline: var_isOnline,
        );
      case 6:
        var var_message = sse_decode_String(deserializer);
        return KoriumEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DhtPeer> sse_decode_list_dht_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DhtPeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dht_peer(deserializer));
    }
    return ans_;
  }

  @protected
  List<KoriumEvent> sse_decode_list_korium_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KoriumEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_korium_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageStatus sse_decode_message_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageStatus.values[inner];
  }

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageType.values[inner];
  }

  @protected
  NodeConfig sse_decode_node_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bindAddr = sse_decode_String(deserializer);
    var var_namespaceSecret = sse_decode_opt_String(deserializer);
    var var_privateKeyHex = sse_decode_opt_String(deserializer);
    var var_identityProofNonce = sse_decode_opt_box_autoadd_u_64(deserializer);
    return NodeConfig(
      bindAddr: var_bindAddr,
      namespaceSecret: var_namespaceSecret,
      privateKeyHex: var_privateKeyHex,
      identityProofNonce: var_identityProofNonce,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IdentityRestoreData? sse_decode_opt_box_autoadd_identity_restore_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_identity_restore_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as KoriumNodeImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as KoriumNodeImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as KoriumNodeImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_message_status(MessageStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_message_type(MessageType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KoriumNodeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KoriumNodeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKoriumNode(
    KoriumNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KoriumNodeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(
    ChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_identity_restore_data(
    IdentityRestoreData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_identity_restore_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_node_config(
    NodeConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_node_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.recipientId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_message_type(self.messageType, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_message_status(self.status, serializer);
    sse_encode_bool(self.isFromMe, serializer);
    sse_encode_opt_String(self.replyToId, serializer);
    sse_encode_opt_String(self.mediaUrl, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
    sse_encode_opt_box_autoadd_i_64(self.mediaSizeBytes, serializer);
    sse_encode_opt_box_autoadd_i_64(self.mediaDurationMs, serializer);
  }

  @protected
  void sse_encode_dht_peer(DhtPeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.identity, serializer);
    sse_encode_list_String(self.addresses, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_restore_data(
    IdentityRestoreData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKeyHex, serializer);
    sse_encode_u_64(self.powNonce, serializer);
  }

  @protected
  void sse_encode_korium_error(KoriumError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case KoriumError_BindError(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_BootstrapError(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_ConnectionError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_SendError(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_ReceiveError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_PeerNotFound(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_Timeout(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_InvalidIdentity(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_SerializationError(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
      case KoriumError_NotInitialized():
        sse_encode_i_32(9, serializer);
      case KoriumError_ShutDown():
        sse_encode_i_32(10, serializer);
      case KoriumError_Internal(field0: final field0):
        sse_encode_i_32(11, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_korium_event(KoriumEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case KoriumEvent_PubSubMessage(
        topic: final topic,
        fromIdentity: final fromIdentity,
        data: final data,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(topic, serializer);
        sse_encode_String(fromIdentity, serializer);
        sse_encode_list_prim_u_8_strict(data, serializer);
      case KoriumEvent_IncomingRequest(
        fromIdentity: final fromIdentity,
        requestId: final requestId,
        data: final data,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(fromIdentity, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_list_prim_u_8_strict(data, serializer);
      case KoriumEvent_ChatMessageReceived(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_chat_message(message, serializer);
      case KoriumEvent_MessageStatusUpdate(
        messageId: final messageId,
        status: final status,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_message_status(status, serializer);
      case KoriumEvent_ConnectionStateChanged(isConnected: final isConnected):
        sse_encode_i_32(4, serializer);
        sse_encode_bool(isConnected, serializer);
      case KoriumEvent_PeerPresenceChanged(
        peerIdentity: final peerIdentity,
        isOnline: final isOnline,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(peerIdentity, serializer);
        sse_encode_bool(isOnline, serializer);
      case KoriumEvent_Error(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dht_peer(List<DhtPeer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dht_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_korium_event(
    List<KoriumEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_korium_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_status(MessageStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_node_config(NodeConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bindAddr, serializer);
    sse_encode_opt_String(self.namespaceSecret, serializer);
    sse_encode_opt_String(self.privateKeyHex, serializer);
    sse_encode_opt_box_autoadd_u_64(self.identityProofNonce, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_identity_restore_data(
    IdentityRestoreData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_identity_restore_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class KoriumNodeImpl extends RustOpaque implements KoriumNode {
  // Not to be used by end users
  KoriumNodeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KoriumNodeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KoriumNode,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KoriumNode,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KoriumNodePtr,
  );

  /// Bootstraps the node by connecting to an existing peer.
  ///
  /// # Arguments
  /// * `peer_identity` - The identity (hex) of the bootstrap peer
  /// * `peer_addrs` - List of addresses to try for this peer
  Future<void> bootstrap({
    required String peerIdentity,
    required List<String> peerAddrs,
  }) => RustLib.instance.api.crateApiKoriumNodeBootstrap(
    that: this,
    peerIdentity: peerIdentity,
    peerAddrs: peerAddrs,
  );

  /// Returns the bootstrap error message if bootstrap failed.
  /// Returns None if bootstrap succeeded or hasn't been attempted.
  String? get bootstrapError =>
      RustLib.instance.api.crateApiKoriumNodeBootstrapError(that: this);

  /// Finds peers near a target identity in the DHT.
  ///
  /// # Arguments
  /// * `target_id` - The target identity to search near
  ///
  /// # Returns
  /// List of peer identities found.
  Future<List<String>> findPeers({required String targetId}) => RustLib
      .instance
      .api
      .crateApiKoriumNodeFindPeers(that: this, targetId: targetId);

  /// Gets peers from the DHT routing table.
  ///
  /// Searches for peers near this node's identity in the DHT.
  /// Returns a list of peers with their identities and addresses.
  Future<List<DhtPeer>> getDhtPeers() =>
      RustLib.instance.api.crateApiKoriumNodeGetDhtPeers(that: this);

  /// Returns identity restoration data for saving to secure storage.
  ///
  /// This method returns the private key and PoW nonce needed to restore
  /// the node's identity on subsequent app launches without re-computing PoW.
  ///
  /// # Security
  /// - MUST be stored in secure storage (iOS Keychain / Android Keystore)
  /// - This method can only be called ONCE per node instance
  /// - Subsequent calls return None (one-shot extraction to minimize exposure)
  /// - The secret key allows full identity impersonation - treat as password
  ///
  /// # Returns
  /// - `Some(IdentityRestoreData)` on first call after node creation
  /// - `None` on subsequent calls (data already extracted)
  IdentityRestoreData? getIdentityRestoreData() =>
      RustLib.instance.api.crateApiKoriumNodeGetIdentityRestoreData(that: this);

  /// Returns the node's identity (Ed25519 public key as hex string).
  String get identity =>
      RustLib.instance.api.crateApiKoriumNodeIdentity(that: this);

  /// Returns whether the node has successfully bootstrapped to the Korium network.
  bool get isBootstrapped =>
      RustLib.instance.api.crateApiKoriumNodeIsBootstrapped(that: this);

  /// Checks if a peer is reachable by resolving their address.
  /// Returns true if the peer has published addresses, false otherwise.
  Future<bool> isPeerOnline({required String peerId}) => RustLib.instance.api
      .crateApiKoriumNodeIsPeerOnline(that: this, peerId: peerId);

  /// Returns the local address the node is listening on.
  String get localAddr =>
      RustLib.instance.api.crateApiKoriumNodeLocalAddr(that: this);

  /// Returns the primary routable address for DHT publishing.
  ///
  /// This returns the first non-loopback routable address, suitable for
  /// peer discovery.
  Future<String> primaryRoutableAddress() =>
      RustLib.instance.api.crateApiKoriumNodePrimaryRoutableAddress(that: this);

  /// Publishes a message to a PubSub topic.
  ///
  /// # Arguments
  /// * `topic` - The topic to publish to
  /// * `data` - The message data
  Future<void> publish({required String topic, required List<int> data}) =>
      RustLib.instance.api.crateApiKoriumNodePublish(
        that: this,
        topic: topic,
        data: data,
      );

  /// Publishes the node's address for peer discovery.
  ///
  /// # Arguments
  /// * `addresses` - List of addresses where this node can be reached
  Future<void> publishAddress({required List<String> addresses}) => RustLib
      .instance
      .api
      .crateApiKoriumNodePublishAddress(that: this, addresses: addresses);

  /// Resolves a peer's contact information.
  ///
  /// # Arguments
  /// * `peer_id` - The identity to resolve
  ///
  /// # Returns
  /// List of addresses where the peer can be reached.
  Future<List<String>> resolvePeer({required String peerId}) => RustLib
      .instance
      .api
      .crateApiKoriumNodeResolvePeer(that: this, peerId: peerId);

  /// Returns routable addresses for this node.
  ///
  /// When bound to `0.0.0.0`, this enumerates all local network interfaces
  /// and returns their addresses with the bound port. This is suitable for
  /// peer discovery.
  ///
  /// Loopback addresses (127.0.0.1) are excluded.
  Future<List<String>> routableAddresses() =>
      RustLib.instance.api.crateApiKoriumNodeRoutableAddresses(that: this);

  /// Sends a chat message to a peer.
  ///
  /// # Arguments
  /// * `peer_id` - The identity of the recipient
  /// * `message` - The chat message to send
  ///
  /// # Returns
  /// The sent message with updated status.
  Future<ChatMessage> sendMessage({
    required String peerId,
    required ChatMessage message,
  }) => RustLib.instance.api.crateApiKoriumNodeSendMessage(
    that: this,
    peerId: peerId,
    message: message,
  );

  /// Sends a request to a peer and waits for a response.
  ///
  /// # Arguments
  /// * `peer_id` - The identity of the target peer
  /// * `data` - The request data
  ///
  /// # Returns
  /// The response data from the peer.
  Future<Uint8List> sendRequest({
    required String peerId,
    required List<int> data,
  }) => RustLib.instance.api.crateApiKoriumNodeSendRequest(
    that: this,
    peerId: peerId,
    data: data,
  );

  /// Gracefully shuts down the node.
  Future<void> shutdown() =>
      RustLib.instance.api.crateApiKoriumNodeShutdown(that: this);

  /// Starts listening for incoming messages and requests.
  /// This spawns background tasks that forward events to the event broadcaster.
  /// Call this after node creation to receive incoming messages.
  Future<void> startListeners() =>
      RustLib.instance.api.crateApiKoriumNodeStartListeners(that: this);

  /// Subscribes to a PubSub topic.
  ///
  /// # Arguments
  /// * `topic` - The topic name to subscribe to
  Future<void> subscribe({required String topic}) => RustLib.instance.api
      .crateApiKoriumNodeSubscribe(that: this, topic: topic);
}
