// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'message.freezed.dart';

/// A chat message.
@freezed
sealed class ChatMessage with _$ChatMessage {
  const factory ChatMessage({
    required String id,
    required String senderId,
    required String recipientId,
    required String text,
    required MessageType messageType,
    required PlatformInt64 timestampMs,
    required MessageStatus status,
    required bool isFromMe,
    String? replyToId,
    String? mediaUrl,
    String? thumbnailUrl,
    PlatformInt64? mediaSizeBytes,
    PlatformInt64? mediaDurationMs,
  }) = _ChatMessage;
}

/// Status of a chat message.
enum MessageStatus {
  /// Message is pending to be sent.
  pending,

  /// Message has been sent to the network.
  sent,

  /// Message has been delivered to the recipient.
  delivered,

  /// Message has been read by the recipient.
  read,

  /// Message failed to send.
  failed,
}

/// Type of chat message.
enum MessageType {
  /// Plain text message.
  text,

  /// Image message.
  image,

  /// Video message.
  video,

  /// Audio message.
  audio,

  /// Document/file message.
  document,

  /// Location message.
  location,

  /// Contact card message.
  contact,
}
