// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'message.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'streams.freezed.dart';

@freezed
sealed class KoriumEvent with _$KoriumEvent {
  const KoriumEvent._();

  /// A PubSub message was received
  const factory KoriumEvent.pubSubMessage({
    required String topic,
    required String fromIdentity,
    required Uint8List data,
  }) = KoriumEvent_PubSubMessage;

  /// A direct request was received (needs response)
  const factory KoriumEvent.incomingRequest({
    required String fromIdentity,
    required String requestId,
    required Uint8List data,
  }) = KoriumEvent_IncomingRequest;

  /// A chat message was received
  const factory KoriumEvent.chatMessageReceived({
    required ChatMessage message,
  }) = KoriumEvent_ChatMessageReceived;

  /// A message status update was received (delivery/read receipt)
  const factory KoriumEvent.messageStatusUpdate({
    required String messageId,
    required MessageStatus status,
  }) = KoriumEvent_MessageStatusUpdate;

  /// Connection state changed
  const factory KoriumEvent.connectionStateChanged({
    required bool isConnected,
  }) = KoriumEvent_ConnectionStateChanged;

  /// A peer came online or went offline
  const factory KoriumEvent.peerPresenceChanged({
    required String peerIdentity,
    required bool isOnline,
  }) = KoriumEvent_PeerPresenceChanged;

  /// An error occurred
  const factory KoriumEvent.error({required String message}) =
      KoriumEvent_Error;
}
